language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - /bin/bash ./.travis.sh
  - phpenv rehash
  - composer --dev --prefer-source --no-interaction install

script: vendor/bin/phpunit
